name: Milestone Changelog

# Description of the workflow
description: Re-generates changelog for a given milestone

inputs:
  milestone:
    description: Milestone object containing number and title
    required: true
  token:
    description: GitHub token
    required: true

runs:
  using: "composite"
  steps:
    - name: Parse input
      id: args
      uses: actions/github-script@v6
      env:
        milestone: ${{ inputs.milestone }}
      with:
        script: |
          const inputs = JSON.parse(process.env.milestone);
          console.log(inputs);
          core.setOutput("milestone_title", inputs.milestone.title);
          core.setOutput("milestone_number", inputs.milestone.number);
          console.log("milestone: " + milestone);
          console.log("milestone_title: " + milestone.title);
          console.log("milestone_number: " + milestone.number);

    - name: Collect Changelog
      id: changelog
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.token }}
        script: |
          const fs = require('fs');
          const scopes = new Set([
            "api",
            "vm",
            "vmop",
            "vmbda",
            "vmclass",
            "vmip",
            "vmipl",
            "vdsnapshot",
            "vmsnapshot",
            "vmrestore",
            "disks",
            "vd",
            "images",
            "vi",
            "cvi",
            "core",
            "api-service",
            "vm-route-forge",
            "kubevirt",
            "kube-api-rewriter",
            "cdi",
            "dvcr",
            "module",
            "observability"
          ]);
          
          const types = new Set(["feat", "fix"]);
          const milestoneTitle = core.getInput('milestone_title');
          const milestoneNum = core.getInput('milestone_number');
          console.log(`milestoneTitle: ${milestoneTitle}`);
          console.log(`milestoneNum: ${milestoneNum}`);

          const { data: prs } = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100,
          });

          let result = '';
          prs.forEach(pr => {
              if (pr.milestone === milestoneNum) {
                  const title = pr.title.trim();
                  
                  const match = title.match(/^([a-zA-Z]+)\(([^)]*)\): (.*)$/);
                  
                  if (match) {
                      const type = match[1];
                      const scopeString = match[2];
                      const subject = match[3];

                      // Parse the scopes into an array and check if they all belong to the provided Set
                      const scopesInTitle = scopeString.split(',').map(scope => scope.trim());
                      const validScope = scopesInTitle.every(scope => scopes.has(scope));
                      
                      // Check if the type is valid
                      const validType = types.has(type);
                      
                      // If both type and scope are valid, append to the result string
                      if (validType && validScope) {
                        result += `[pr${pr.number}](${pr.html_url}): ${type}(${scopeString}): ${subject}\n`;
                      }
                  }
              }
          });
          const filename = `CHANGELOG-${milestoneTitle}.md`;
          fs.writeFileSync(filename, result.trim());
          console.log(`Generated changelog for milestone ${milestoneTitle} with filtered commits.`);


    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        commit-message: |
          Re-generate changelog ${{ steps.args.outputs.milestone_title }}

          Signed-off-by: deckhouse-BOaTswain <89150800+deckhouse-boatswain@users.noreply.github.com>
        base: main
        branch: changelog/${{ steps.args.outputs.milestone_title }}
        milestone: ${{ steps.args.outputs.milestone_number }}
        title: Changelog ${{ steps.args.outputs.milestone_title }}
        body: |
          The changelog for milestone **${{ steps.args.outputs.milestone_title }}** has been generated.

          For details, see the [changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG/CHANGELOG-${{ steps.args.outputs.milestone_title }}.md).
        labels: changelog, auto, status/backport
        token: ${{ inputs.token }}
        delete-branch: true
